# Configuration for the Dependency Review GitHub Action

# Fail the action if any vulnerabilities are found
fail-on-severity: moderate

# Allow specific licenses
allow-licenses:
  - MIT
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - GPL-3.0
  - MPL-2.0

# Deny specific licenses  
deny-licenses:
  - GPL-2.0
  - LGPL-2.1

# Allow dependencies from specific scopes/namespaces
allow-dependencies-licenses:
  - npm: "@types/*"
  - go: "github.com/gitleaks/*"
  - go: "github.com/google/*"
  - go: "github.com/palantir/*"
  - go: "github.com/rs/*"
  - go: "golang.org/*"
  - go: "google.golang.org/*"
  - go: "gopkg.in/*"

# Comment summary in pull requests
comment-summary-in-pr: true

# Retry configuration
retry-on-snapshot-warnings: true

# Warn about direct dependencies
warn-only: false 