version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: gitguard
    main: ./main.go
    binary: gitguard
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - windows
      - darwin
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: gitguard
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

kos:
  - id: gitguard-ko
    build: gitguard
    main: .
    working_dir: .
    base_image: cgr.dev/chainguard/static
    labels:
      org.opencontainers.image.title: GitGuard
      org.opencontainers.image.description: A GitHub App for detecting secrets in commits using Gitleaks
      org.opencontainers.image.source: https://github.com/omercnet/gitguard
      org.opencontainers.image.vendor: omercnet
    annotations:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.revision: "{{.Commit}}"
      org.opencontainers.image.version: "{{.Version}}"
    repositories:
      - ghcr.io/omercnet/gitguard
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - "{{.Version}}"
      - "{{if not .Prerelease}}stable{{end}}"
      - latest
    creation_time: "{{.CommitTimestamp}}"
    ko_data_creation_time: "{{.CommitTimestamp}}"
    sbom: spdx
    sbom_directory: "out/sbom"

changelog:
  disable: true

release:
  github:
    owner: omercnet
    name: gitguard
