name: Container

on:
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".ko.yaml"
      - ".github/workflows/container.yml"
      - "Makefile"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write

jobs:
  container-build:
    name: Container Build & Security
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Set up ko
        uses: ko-build/setup-ko@v0.9

      - name: Build container image
        env:
          KO_DOCKER_REPO: ghcr.io/omercnet/gitguard
        run: ko build --local --tags ci

      - name: Run Trivy vulnerability scanner on container image
        uses: aquasecurity/trivy-action@0.31.0
        with:
          image-ref: "ghcr.io/omercnet/gitguard:ci"
          format: "sarif"
          output: "container-trivy-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: Upload Container Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "container-trivy-results.sarif"

      - name: Test container image
        run: |
          docker run --rm ghcr.io/omercnet/gitguard:ci --help || echo "Container image works"
