name: Manual Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write
  packages: write
  id-token: write # For cosign keyless signing
  attestations: write # For build attestations

env:
  KO_DOCKER_REPO: ghcr.io/omercnet

jobs:
  manual-release:
    name: Manual Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run tests before release
        run: |
          go test -v ./...

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.6.0
        with:
          cosign-release: 'v2.2.4'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up OIDC token for cosign
        run: |
          echo "COSIGN_EXPERIMENTAL=1" >> $GITHUB_ENV

      - name: Install ko
        uses: ko-build/setup-ko@v0.7
        with:
          version: v0.15.4

      - name: Build and push container image
        run: |
          # Build and push the container image
          ko build --tags latest --tags ${{ github.event.inputs.tag }} .
          
          # Sign the container image
          cosign sign --yes ghcr.io/omercnet/gitguard:${{ github.event.inputs.tag }}
          cosign sign --yes ghcr.io/omercnet/gitguard:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KO_DOCKER_REPO: ${{ env.KO_DOCKER_REPO }}
          COSIGN_EXPERIMENTAL: 1 